[package]
name = "secret-sharing"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shamir-split"

[[bin]]
name = "shamir-combine"

[dependencies]
clap = { version = "3.1.17", features = ["derive"] }
rand = "0.8.5"
